# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
# alt-enter = exec-and-forget open -n /System/Applications/Alacritty.app

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-j = 'move-through left'
alt-shift-k = 'move-through down'
alt-shift-l = 'move-through up'
alt-shift-semicolon = 'move-through right'

alt-b = 'split horizontal'
alt-m = 'split vertical'

alt-f = 'fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://github.com/nikitabobko/AeroSpace/blob/main/docs/guide.md#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they should be supported at all
# https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
#alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
#alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode esc'

[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 40
outer.right = 0


[workspace-to-monitor-force-assignment]
1 = '2'                            # Monitor sequence number from left to right. 1-based indexing
2 = '2'                       # Main monitor
3 = '3'                  # Non-main monitor in case when there are only two monitors
4 = '4'                   # Case insensitive regex substring
5 = '2'  # Case insensitive regex match
6 = ['secondary', 'dell']        # You can specify multiple patterns. The first matching pattern will be used


# Notify Sketchybar about workspace change
# exec-on-workspace-change = [
# 	'/bin/bash',
# 	'-c',
# 	'/opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
# ]
